version: '3.5'

services:
  nginx:
    image: nginx:1.21-alpine
    env_file:
      - .env
    ports:
      - "8081:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - web

  web:
    build: .
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    env_file:
      - .env
    ports:
      - "6380:${REDIS_PORT}"
